import Navbar from "@/components/navbar";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Navbar />
        {children}
        <script
          id="bot-script"
          bot_id="a705d018-3c29-4996-b87b-a3e4146c8f60"
          org_id="Pace_wisdom_29102023"
          primary_color="black"
          default_message="Hey there, ask questions related to our services."
          bot_name="Tailor Talks"
          bot_height=""
          bot_width=""
          white_label="true" //false if wl not needed
          text_color="white"
          src="https://tailortalk.netlify.app/chat-plugin.js"
        ></script>
      </body>
    </html>
  );
}
