import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Tailor Talk",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="montserrat-unique">
          {/* Content using Montserrat font */}
          {children}
        </div>
        <div className="open-sans-unique">
          {/* Content using Open Sans font */}
        </div>
      </body>
    </html>
  );
}
