import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header.js";
import Footer from "./components/Footer.js";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Tailor Talk",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} montserrat-unique`}>
        <Header/>
        {/* Content */}
        {children}
        <Footer />
      </body>
    </html>
  );
}
