export const testimonials = [
  {
    company: "Keerthi Triumph",
    title: "Hundreds of Hours Saved Automating Bike Inquiries & Bookings",
    text: "TailorTalk automates everything from exploring models and scheduling test rides to booking service appointments via WhatsApp chat. This efficiency has saved our team hundreds of valuable manual hours.",
    logo: "/keerthi.jpg",
    person: "Emily Smith",
    role: "CEO",
  },
  {    
    company: "CF Tech",
    title: "Exhibition QR Code Turned Visitors into Sales Leads",
    text: "Using a simple WhatsApp QR code at our exhibition, TailorTalk engaged visitors, collected contacts, and automatically followed up. This turned event interest into real sales conversations and opportunities for us.",
    logo: "/cf_tech.jpg",
    person: "Sarah Johnson",
    role: "Project Manager",
},
  {
    company: "Tootly",
    title: "Doubled Revenue by Automating Instagram Lead Handling",
    text: "We struggled to scale Instagram ad leads manually. TailorTalk now handles 2.5x the lead volume automatically, directly resulting in a 2x increase in our revenue. It's been a game-changer.",
    logo: "/tootly.jpg",
    person: "David Johnson",
    role: "Founder",
  },
  {
    company: "Rage Room",
    title: "Seamless WhatsApp Bookings, Instantly Confirmed",
    text: "TailorTalk guides customers through our packages on WhatsApp, confirms bookings instantly, and sends details straight to our team. It completely streamlined our booking process.",
    logo: "/rageroom.jpg",
    person: "Mark Thompson",
    role: "CEO",
  },
  {
    company: "CoachDirect",
    title: "Delightful Coach Bookings & Reduced Manual Effort",
    text: "TailorTalk instantly recommends the right coaches and answers queries on WhatsApp, making bookings smooth and efficient. It significantly cut down our manual workload.",
    logo: "/coach_direct.jpg",
    person: "John Deo",
    role: "Founder",
  },
  {
    company: "Samyak Sarees",
    title: "Freed Our Team by Automating 1000+ Daily Instagram Enquiries",
    text: "TailorTalk connects seamlessly to our backend via API, instantly handling over 1000 customer enquiries on Instagram every day. This crucial automation frees our team to focus on growth and other strategic priorities instead of repetitive chat.",
    logo: "/Samyakk.webp",
    person: "Emily Smith",
    role: "CEO",
  },
{
  company: "Stallions",
  title: "Freed Our Team by Automating 1000+ Daily Instagram Enquiries",
  text: "TailorTalk connects seamlessly to our backend via API, instantly handling over 1000 customer enquiries on Instagram every day. This crucial automation frees our team to focus on growth and other strategic priorities instead of repetitive chat.",
  logo: "/stallions.png",
  person: "Emily Smith",
  role: "CEO",
}
];